### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/MTOR_ligand_smiles.txt'

### ISSUE THREAD

**Issue by zimengc** [bpmunson/polygon#9]
Dear authors:

I met another traceback after downloading ·fpscores.pkl.gz· and updating the file path.

Traceback detail:
```
2024-08-07 21:50:17,789 [DEBUG   ] Making scoring function,
Traceback (most recent call last):
  File "/home/zimengch/.local/bin/polygon", line 8, in <module>
    sys.exit(main())
  File "/home/zimengch/.local/lib/python3.9/site-packages/polygon/run.py", line 844, in main
    generate_main(args)
  File "/home/zimengch/.local/lib/python3.9/site-packages/polygon/run.py", line 659, in generate_main
    scoring_function = build_scoring_function(
  File "/home/zimengch/.local/lib/python3.9/site-packages/polygon/utils/utils.py", line 289, in build_scoring_function
    with open(row.file) as handle:
FileNotFoundError: [Errno 2] No such file or directory: '../data/MTOR_ligand_smiles.txt'
```

Other than  `'../data/MTOR_ligand_smiles.txt'`, I think all four files starts with `.../data/` are missing as well. 

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/fe586aca-2808-470d-bfcd-1bfb1732face">

So may you please provide these four files, or share the steps to create them? Thank you!

Best,
Zimeng

**Comment by BOYA1999** [comment]
use linux and change your path ,虚拟机不行，进不去的
